version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #PGDATA:
      #POSTGRES_INITDB_ARGS
      #POSTGRES_INITDB_WALDIR
      #POSTGRES_HOST_AUTH_METHOD
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

